- name: Reproduce ouptuts with JDLL 0.5.5-SNAPSHOT (tensorflow_saved_model_bundle)
  status: failed
  error: "java.lang.IllegalArgumentException: Processing method 'python' failed throwing\
    \ an InvocationTargetException. Go to the following link to see valid transformations:https://github.com/bioimage-io/core-bioimage-io-java/tree/master/src/main/java/io/bioimage/specification/transformation.\
    \ \n\njava.lang.IllegalArgumentException: No executables found amongst candidates:\
    \ [python, python.exe, bin/python, bin/python.exe]"
  traceback: "java.lang.IllegalArgumentException: Processing method 'python' failed\
    \ throwing an InvocationTargetException. Go to the following link to see valid\
    \ transformations:https://github.com/bioimage-io/core-bioimage-io-java/tree/master/src/main/java/io/bioimage/specification/transformation.\
    \ \n\njava.lang.IllegalArgumentException: No executables found amongst candidates:\
    \ [python, python.exe, bin/python, bin/python.exe]"
  source_name: /home/runner/work/icy-bioimage-io/icy-bioimage-io/bioimageio-gh-pages/rdfs/10.5281/zenodo.6338614/6338615/rdf.yaml
  JDLL_VERSION: 0.5.5-SNAPSHOT
